// Browser-safe mock for Tauri invoke — used when running outside the desktop app
import { ServerConfig } from "./types";

const MOCK_CONFIG: ServerConfig = {
  server_path: "/Users/demo/minecraft-server",
  java_path: "/usr/bin/java",
  minecraft_version: "1.21.1",
  server_type: "paper",
  loader_version: "132",
  ram_mb: 2048,
  max_players: 10,
  server_name: "My Minecraft Server",
  setup_complete: true,
  auto_restart: true,
  backup_interval_minutes: 0,
  backup_dir: "",
  backup_include_logs: false,
  optimized_jvm_flags: true,
  performance_preset: "balanced",
  remote_control_enabled: false,
  remote_control_port: 47992,
  remote_control_token: "",
  remote_control_public_url: "",
  cloudflare_remote_enabled: false,
};

const handlers: Record<string, (...args: unknown[]) => unknown> = {
  get_config: () => ({ ...MOCK_CONFIG }),
  save_config: (args?: unknown) => (args as { cfg?: ServerConfig } | undefined)?.cfg ?? { ...MOCK_CONFIG },
  check_java: () => "/usr/bin/java",
  fetch_mc_versions: () => [
    { id: "1.21.1", release_time: "2024-08-08T12:00:00Z" },
    { id: "1.21",   release_time: "2024-06-13T12:00:00Z" },
    { id: "1.20.6", release_time: "2024-04-29T12:00:00Z" },
    { id: "1.20.4", release_time: "2023-12-07T12:00:00Z" },
    { id: "1.20.1", release_time: "2023-06-12T12:00:00Z" },
    { id: "1.19.4", release_time: "2023-03-14T12:00:00Z" },
  ],
  fetch_paper_versions: () => ["1.21.1", "1.21", "1.20.6", "1.20.4", "1.19.4"],
  fetch_paper_builds: () => [{ version: "132", label: "132 (latest)" }],
  fetch_forge_versions: () => [
    { version: "49.0.48", label: "49.0.48 (recommended)" },
    { version: "49.2.0",  label: "49.2.0 (latest)" },
  ],
  fetch_fabric_versions: () => [{ version: "0.15.11", label: "0.15.11 (latest)" }],
  fetch_neoforge_versions: () => [{ version: "20.4.244", label: "20.4.244 (latest)" }],
  default_server_path: () => "/Users/demo/minecraft-server",
  get_server_status: () => "running",
  get_server_stats: () => ({
    cpu_percent: 42.4, ram_used_mb: 1340, ram_max_mb: 2048,
    disk_read_kb_s: 12.3, disk_write_kb_s: 142.7,
    disk_used_mb: 412_000, disk_total_mb: 1_000_000,
    tps: 19.6,
    players_online: 2, players_max: 10, uptime_seconds: 3725,
  }),
  get_playit_status: () => ({ running: false, address: null, claim_url: null, pid: null }),
  check_for_update: () => ({
    current_version: "0.1.2",
    latest_version: "0.1.2",
    update_available: false,
    release_name: "v0.1.2 — Branding, Performance & Admin Tools",
    release_url: "https://github.com/GGF-GameForFun/GGF-GameForFun/releases/latest",
    release_notes: "",
  }),
  open_update_url: () => undefined,
  generate_remote_token: () => "demo-token-1234567890",
  get_remote_control_status: () => ({
    enabled: MOCK_CONFIG.remote_control_enabled,
    running: false,
    host: "127.0.0.1",
    port: MOCK_CONFIG.remote_control_port,
    token: MOCK_CONFIG.remote_control_token,
    lan_url: "",
    public_url: "",
    url: "",
  }),
  restart_remote_control: () => ({
    enabled: true,
    running: true,
    host: "127.0.0.1",
    port: MOCK_CONFIG.remote_control_port,
    token: MOCK_CONFIG.remote_control_token || "demo-token-1234567890",
    lan_url: "http://127.0.0.1:47992/?token=demo-token-1234567890",
    public_url: "",
    url: "http://127.0.0.1:47992/?token=demo-token-1234567890",
  }),
  get_cloudflare_remote_status: () => ({
    running: false,
    url: null,
    pid: null,
    message: "",
  }),
  start_cloudflare_remote: () => ({
    running: true,
    url: "https://demo.trycloudflare.com",
    pid: 1234,
    message: "Cloudflare tunnel ready.",
  }),
  stop_cloudflare_remote: () => ({
    running: false,
    url: null,
    pid: null,
    message: "Cloudflare tunnel stopped.",
  }),
  start_server: () => undefined,
  stop_server: () => undefined,
  restart_server: () => undefined,
  send_command: () => undefined,
  get_recent_players: () => [["DemoPlayer1", new Date(Date.now() - 600_000).toISOString()]],
  get_banned_players: () => [
    {
      name: "BadSteve",
      uuid: "00000000-0000-0000-0000-000000000000",
      created: new Date(Date.now() - 3_600_000).toISOString(),
      source: "Server",
      expires: "forever",
      reason: "Banned by an operator.",
    },
  ],
  unban_player: () => [],
  // ── Mocks added for browser-mode design preview ──────────────────────
  get_online_players: () => ["Fishgod212", "Aingker"],
  get_console_buffer: () => [
    "[12:00:14] [Server thread/INFO]: Starting minecraft server version 1.20.1",
    "[12:00:18] [Server thread/INFO]: Loading properties",
    "[12:00:21] [Server thread/INFO]: Default game type: SURVIVAL",
    "[12:00:32] [Server thread/INFO]: Preparing level \"world\"",
    "[12:00:45] [Server thread/INFO]: Done (12.451s)! For help, type \"help\"",
    "[12:01:03] [Server thread/INFO]: Fishgod212 joined the game",
    "[12:01:18] [Server thread/INFO]: <Fishgod212> hello world",
    "[12:02:44] [Server thread/INFO]: Aingker joined the game",
    "[12:03:01] [Server thread/INFO]: <Aingker> ready to host?",
    "[mchost] Auto-backup created: 312 files, 84.2 MB",
  ],
  clear_console_buffer: () => undefined,
  get_pregen_state: () => ({ running: false, total: 0, completed: 0, cancel_requested: false }),
  pregenerate_chunks: () => undefined,
  cancel_pregenerate: () => undefined,
  get_tunnel_diagnostics: () => ({
    agent_running: true,
    has_secret: true,
    has_address: true,
    address: "demo-tunnel.joinmc.link:25565",
    server_running: true,
    local_port: 25565,
  }),
  default_backup_filename: () => "[Backup]-08-05-2026.zip",
  default_debug_filename: () => "debug-report-08-05-2026.zip",
  default_downloads_dir: () => "/Users/demo/Downloads",
  create_backup: () => ({ files: 312, bytes: 84_200_000, path: "/Users/demo/Downloads/[Backup]-08-05-2026.zip" }),
  restore_backup: () => 312,
  export_debug: () => 8,
  force_quit: () => undefined,
  list_mods: () => [
    "create-1.20.1-0.5.1.f.jar",
    "jei-1.20.1-15.3.0.8.jar",
    "sodium-fabric-0.5.8.jar",
    "iris-fabric-1.6.17.jar",
    "supplementaries-1.20-3.0.16.jar",
    "EssentialsX-2.20.1.jar",
    "WorldEdit-7.3.0.jar",
  ],
  add_mod: () => undefined,
  remove_mod: () => undefined,
  get_server_properties: () => ({
    "online-mode": "false",
    "max-players": "10",
    "motd": "My Minecraft Server",
    "server-port": "25565",
    "difficulty": "normal",
    "gamemode": "survival",
    "pvp": "true",
    "view-distance": "10",
  }),
  save_server_properties: () => undefined,
  setup_playit: () => undefined,
  start_playit: () => undefined,
  stop_playit: () => undefined,
  refresh_playit_address: () => ({ running: true, address: "example.playit.gg:25565", claim_url: null, pid: 1234 }),
  open_server_folder: () => undefined,
  install_server: () => ({ ...MOCK_CONFIG, setup_complete: true }),
};

export function mockInvoke(cmd: string, _args?: unknown): Promise<unknown> {
  const handler = handlers[cmd];
  if (handler) return Promise.resolve(handler(_args));
  console.warn(`[mock] unhandled invoke: ${cmd}`);
  return Promise.resolve(null);
}

export function mockListen(
  _event: string,
  _cb: (e: { payload: unknown }) => void
): Promise<() => void> {
  return Promise.resolve(() => {});
}
